<?php

namespace Database\Seeders;

use App\Models\Genre;
use Illuminate\Database\Seeder;

class GenreSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       $genre = new Genre(); $genre->name = 'Acid'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Acid jazz'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Acid punk'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Acid rap'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Acid rock'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Acid techno'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Afoxé'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Afro'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Afro-Cuban jazz'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Afro-juju'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Afro-punk'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Afrobeat'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Aggrotech'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Air'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Alternative   '; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Alternative & Rock in Spanish'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Ambient'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Americana'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Anadolu rock'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Anarcho-punk'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Andean New Age'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Anime'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Anti-folk'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Arabesk'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Art'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Asian'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Audio Book'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Avant-garde'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Axé'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Bachata'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Baião'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Baila'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Baile Funk'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Bambuco'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Banda'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Bass'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Bastard Pop'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Batá'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Batucada'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Batuco'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Beat'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Beatboxing'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Bebop'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Big band music'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Big Beat'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Bloco afro'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Bluegrass'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Blues'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Bohemian Dub'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Boi'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Bolero'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Bombay pop'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Bossa nova'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Boy band'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Brass'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Brazilian'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Breakbeat'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Bregafunk'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Britpop'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Broken beat'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Bubblegum pop'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Bugio'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Bulerias'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'C-Pop'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Cabaret'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Cadence'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Cajun'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Calypso'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Canção '; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Canto livre'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Cantro nuevo'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Canto popular'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Cantopop/HK-Pop'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Capoeira music'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Carimbó'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Celtic'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Celtic Folk'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Celtic Pop'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Celtic Rock'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Chamamé'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Chamarra'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Chamber music'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Champeta'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Chemical breaks'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = "Children's music"; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Chill-Out'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Chinese'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Chorinho'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Choro'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Christian'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Chumba'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Classical'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Classical Crossover'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Club'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Coldwave'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Comedy'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Cool jazz'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Country'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Creole'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Crunk'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Cumbia'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Currulao'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Dance'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Dancehall'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Dark'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Death industrial'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Death metal'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Deathcore'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Deathgrind'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Deboche'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Deep house'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Deep soul'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Delta blues'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Dembow'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Dini'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Disco'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Dixieland'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Dopé'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Downtempo'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Dreamp pop'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Drill and bass'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Drone'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Drum and bass'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Dub'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Dubstep'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Easy Listening'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Electro'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Electro Backbeat'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Electro hop'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Electronic'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Electronica'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Electropop'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Emo'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Enka'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Europop'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Experimental'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'F-Step'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Fado'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Fantezi'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Filk'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Flamenco'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Folk'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Folktronica'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Forró'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Free improvisation'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Free jazz'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Freestyle'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'French Pop'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Frevo'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Fricote'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Funk'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Gangsta rap'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Garage'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'German Folk'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'German Pop'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Go go'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Gospel'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Gothic'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Crime'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Grindcore'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Groove metal'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Grunge'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Grupera'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Guitarra Baiana'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Gypsy'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Halk'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Hard bop'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Hardcore'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Heavy metal'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Hip Hop '; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Hip Hop/Rap'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Holiday Music'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'House'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Hyphy'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Indian Classical'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Indie'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Indie Pop'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Indo Pop'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Industrial'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Infantil'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Instrumental'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Jam'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Jazz'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Juju'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Jungle'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'K-Pop'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Karaoke'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Kayokyoku'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Kizomba'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Latin'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Latin Jazz'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Latin Rap'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Lo-pop'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Lounge'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Mambo'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Mangue Beat'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Maracatu'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Mariachi'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Marimba'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Maxixe'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Mento'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Merengue'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Metal'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Mexican'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Miami bass'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Microhouse'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Milonga'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Minimalist'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Modinha'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Motown'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'MPB'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Neo Soul'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Neofolk'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'New Age'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'New Wave'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Noise pop'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Norteño'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Nova canção'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Oi!'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Old school'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Old time'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Oldies'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Opera'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Orchestra'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Outlaw'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Özgün'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Pagode'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Pixiefunk'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Plena'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Pop'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Pop in Spanish'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Popular Colombiana'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Porngroove'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Post-hardcore'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Progressive'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Psychedelic'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Psychobilly'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Punk'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Quadrille'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Ragas'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Raggamuffin'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Ragtime'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Rancheira'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Rap'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Rave'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Reggae'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Reggaeton'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Regional Mexicano'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Retro'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Rhythm & Blues'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Rock'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Rock opera'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Rockabilly'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Roots'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Russian Chanson'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Salsa'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Salsa Choke'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Samba'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Samba-canção '; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Samba-reggae'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Sanar'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Sertaneja'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Singer-songwriter'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Ska'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Skate'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Sludge metal'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Smooth jazz'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Soca'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Soldier'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Son montuno'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Sonata'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Sonsureño'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Soul'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Soundtrack'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Southern'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Space'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Speed metal'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Spiritual'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Spirituals'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Spoken Word'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Story'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Surf'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Swing music'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Swingbeat'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Symphony'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Tango'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Techno'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Teen pop'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Thai Pop'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Thrash metal'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Tradicional Colombiana'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Trance'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Trap'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Tribal house'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Trip rock'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Trip-hop'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Tropical'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Tropical Salsa'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Tropicalia'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Turkish '; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Turkish Alternative'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Turkish Hip-Hop/Rap'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Turkish Pop'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Turkish Rock'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Unassigned'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Underground'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Unplugged'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Urban  '; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Urban Cowboy'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Urban Folk'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Urban jazz'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Vallenato'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Valsa'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Vaneira'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Video game'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Vocal'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Waltz'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'West Coast hip hop'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'World'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Worldbeat'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Xote'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Yo-pop'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Zouk'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Zulu'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Zydeco'; $genre->type = 'M'; $genre->save();
       $genre = new Genre(); $genre->name = 'Atmosférico'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Bodas'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Calma'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Celebración'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Ciencia'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Chill'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Cinematográfico'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Comida'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Conciencia social'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Corporativo'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Curioso'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Deporte y Fitness'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Documental'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Educación'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Elegante'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Épico'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Espiritual'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Etéreo'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Estilo de vida'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Étnico'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Exótico'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Folclórico'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Industrial'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Inspirador'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Íntimo'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Lapso de tiempo'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Mediático'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Médico'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Misterioso'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Moda'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Movimiento lento'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Naturaleza'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Negocios y Empresas'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Nocturno'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Pacífico'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Paisaje'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Percusivo'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Reconfortante'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Sentirse bien'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Sobrenatural'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Sofisticado'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Spa'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Suspenso'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Tecnología'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Velocidad'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Viaje  '; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Viaje por carretera'; $genre->type = 'A'; $genre->save();
       $genre = new Genre(); $genre->name = 'Anuncio'; $genre->type = 'A'; $genre->save();       
    }
}
